#!/bin/bash

# On $USER init session:
# open a terminal
# in that terminal execute the script at $LAUNCH_PATH/$LAUNCH_SCRIPT

LAUNCH_PATH="$HOME/scripts/"
LAUNCH_SCRIPT="START.j"

echo
echo "Launching..."
title="Insert tittle here"


xterm -geometry 150x50 -sb -sl 5000 -bg "black" -fg "white" -fn "lucidasanstypewriter-12" -T "$title" -e $LAUNCH_PATH/$LAUNCH_SCRIPT    $USER LINUX 1 &

